#
# Module manifest for module 'Restart-ExchangeServices'
#
# Generated by: asheroto
#
# Generated on: 2021-02-04
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Restart-ExchangeServices.psm1'

# Version number of this module.
ModuleVersion = '0.0.3'

# Supported PSEditions
CompatiblePSEditions = 'Desktop', 'Core'

# ID used to uniquely identify this module
GUID = 'a280f2d1-9b6d-425b-986b-d6c39738a9dc'

# Author of this module
Author = 'asheroto'

# Description of the functionality provided by this module
Description = 'Restarts running Microsoft Exchange services on the server.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Restart-ExchangeServices'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Restart', 'Exchange', 'Server', 'Services'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/asheroto/Restart-ExchangeServices'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}